////////////////////////////////////////////////////////////////////////////////
// action.js
// Describes FF14 actions (for example, GCD, allows weaving, skill delay, etc.)
////////////////////////////////////////////////////////////////////////////////

// NOTE: This information should be seeded via DATs - but does require
// enrichment.

GCD_COOLDOWN = 58;

// Actions Database
const ACTIONS = {
  BLM: [
  {
    "costType": 3,
    "cost": 4,
    "name": "Blizzard",
    "recastTime": 25,
    "level": 1,
    "isRoleAction": false,
    "_id": 142,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000454"
  },
  {
    "costType": 3,
    "cost": 10,
    "name": "Fire",
    "recastTime": 25,
    "level": 2,
    "isRoleAction": false,
    "_id": 141,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000451"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Transpose",
    "recastTime": 120,
    "level": 4,
    "isRoleAction": false,
    "_id": 149,
    "cooldownGroup": 1,
    "castTime": 0,
    "icon": "000466"
  },
  {
    "costType": 3,
    "cost": 8,
    "name": "Thunder",
    "recastTime": 25,
    "level": 6,
    "isRoleAction": false,
    "_id": 144,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000457"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Addle",
    "recastTime": 900,
    "level": 8,
    "isRoleAction": true,
    "_id": 7560,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000861"
  },
  {
    "costType": 3,
    "cost": 10,
    "name": "Sleep",
    "recastTime": 25,
    "level": 10,
    "isRoleAction": false,
    "_id": 145,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000465"
  },
  {
    "costType": 3,
    "cost": 8,
    "name": "Blizzard II",
    "recastTime": 25,
    "level": 12,
    "isRoleAction": false,
    "_id": 146,
    "cooldownGroup": 58,
    "castTime": 20,
    "icon": "000455"
  },
  {
    "costType": 3,
    "cost": 0,
    "name": "Break",
    "recastTime": 25,
    "level": 12,
    "isRoleAction": true,
    "_id": 7558,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000862"
  },
  {
    "costType": 3,
    "cost": 8,
    "name": "Scathe",
    "recastTime": 25,
    "level": 15,
    "isRoleAction": false,
    "_id": 156,
    "cooldownGroup": 58,
    "castTime": 0,
    "icon": "000462"
  },
  {
    "costType": 3,
    "cost": 5,
    "name": "Drain",
    "recastTime": 25,
    "level": 16,
    "isRoleAction": true,
    "_id": 7564,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000863"
  },
  {
    "costType": 3,
    "cost": 15,
    "name": "Fire II",
    "recastTime": 25,
    "level": 18,
    "isRoleAction": false,
    "_id": 147,
    "cooldownGroup": 58,
    "castTime": 30,
    "icon": "000452"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Diversion",
    "recastTime": 1200,
    "level": 20,
    "isRoleAction": true,
    "_id": 7545,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000827"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Lucid Dreaming",
    "recastTime": 1200,
    "level": 24,
    "isRoleAction": true,
    "_id": 7562,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000865"
  },
  {
    "costType": 3,
    "cost": 12,
    "name": "Thunder II",
    "recastTime": 25,
    "level": 26,
    "isRoleAction": false,
    "_id": 7447,
    "cooldownGroup": 58,
    "castTime": 30,
    "icon": "000468"
  },
  {
    "costType": 1,
    "cost": 20,
    "name": "Convert",
    "recastTime": 1800,
    "level": 30,
    "isRoleAction": false,
    "_id": 158,
    "cooldownGroup": 11,
    "castTime": 0,
    "icon": "002651"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Manaward",
    "recastTime": 1200,
    "level": 30,
    "isRoleAction": false,
    "_id": 157,
    "cooldownGroup": 8,
    "castTime": 0,
    "icon": "000463"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Swiftcast",
    "recastTime": 600,
    "level": 32,
    "isRoleAction": true,
    "_id": 7561,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000866"
  },
  {
    "costType": 3,
    "cost": 20,
    "name": "Fire III",
    "recastTime": 25,
    "level": 34,
    "isRoleAction": false,
    "_id": 152,
    "cooldownGroup": 58,
    "castTime": 35,
    "icon": "000453"
  },
  {
    "costType": 3,
    "cost": 20,
    "name": "Freeze",
    "recastTime": 25,
    "level": 35,
    "isRoleAction": false,
    "_id": 159,
    "cooldownGroup": 58,
    "castTime": 30,
    "icon": "002653"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Mana Shift",
    "recastTime": 1200,
    "level": 36,
    "isRoleAction": true,
    "_id": 7565,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000867"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Apocatastasis",
    "recastTime": 900,
    "level": 40,
    "isRoleAction": true,
    "_id": 7563,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000868"
  },
  {
    "costType": 3,
    "cost": 12,
    "name": "Blizzard III",
    "recastTime": 25,
    "level": 40,
    "isRoleAction": false,
    "_id": 154,
    "cooldownGroup": 58,
    "castTime": 35,
    "icon": "000456"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Surecast",
    "recastTime": 300,
    "level": 44,
    "isRoleAction": true,
    "_id": 7559,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000869"
  },
  {
    "costType": 3,
    "cost": 16,
    "name": "Thunder III",
    "recastTime": 25,
    "level": 45,
    "isRoleAction": false,
    "_id": 153,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000459"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Erase",
    "recastTime": 900,
    "level": 48,
    "isRoleAction": true,
    "_id": 7566,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000870"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Aetherial Manipulation",
    "recastTime": 300,
    "level": 50,
    "isRoleAction": false,
    "_id": 155,
    "cooldownGroup": 4,
    "castTime": 0,
    "icon": "000467"
  },
  {
    "costType": 4,
    "cost": 10,
    "name": "Flare",
    "recastTime": 25,
    "level": 50,
    "isRoleAction": false,
    "_id": 162,
    "cooldownGroup": 58,
    "castTime": 40,
    "icon": "002652"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Ley Lines",
    "recastTime": 900,
    "level": 52,
    "isRoleAction": false,
    "_id": 3573,
    "cooldownGroup": 7,
    "castTime": 0,
    "icon": "002656"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Sharpcast",
    "recastTime": 600,
    "level": 54,
    "isRoleAction": false,
    "_id": 3574,
    "cooldownGroup": 5,
    "castTime": 0,
    "icon": "002657"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Enochian",
    "recastTime": 300,
    "level": 56,
    "isRoleAction": false,
    "_id": 3575,
    "cooldownGroup": 3,
    "castTime": 0,
    "icon": "002658"
  },
  {
    "costType": 3,
    "cost": 8,
    "name": "Blizzard IV",
    "recastTime": 25,
    "level": 58,
    "isRoleAction": false,
    "_id": 3576,
    "cooldownGroup": 58,
    "castTime": 28,
    "icon": "002659"
  },
  {
    "costType": 3,
    "cost": 10,
    "name": "Fire IV",
    "recastTime": 25,
    "level": 60,
    "isRoleAction": false,
    "_id": 3577,
    "cooldownGroup": 58,
    "castTime": 28,
    "icon": "002660"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Between the Lines",
    "recastTime": 30,
    "level": 62,
    "isRoleAction": false,
    "_id": 7419,
    "cooldownGroup": 2,
    "castTime": 0,
    "icon": "002661"
  },
  {
    "costType": 3,
    "cost": 18,
    "name": "Thunder IV",
    "recastTime": 25,
    "level": 64,
    "isRoleAction": false,
    "_id": 7420,
    "cooldownGroup": 58,
    "castTime": 30,
    "icon": "002662"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Triplecast",
    "recastTime": 600,
    "level": 66,
    "isRoleAction": false,
    "_id": 7421,
    "cooldownGroup": 16,
    "castTime": 0,
    "icon": "002663"
  },
  {
    "costType": 18,
    "cost": 0,
    "name": "Foul",
    "recastTime": 25,
    "level": 70,
    "isRoleAction": false,
    "_id": 7422,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "002664"
  }
],
  SMN: [
  {
    "costType": 3,
    "cost": 4,
    "name": "Blizzard",
    "recastTime": 25,
    "level": 1,
    "isRoleAction": false,
    "_id": 142,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000454"
  },
  {
    "costType": 3,
    "cost": 10,
    "name": "Fire",
    "recastTime": 25,
    "level": 2,
    "isRoleAction": false,
    "_id": 141,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000451"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Transpose",
    "recastTime": 120,
    "level": 4,
    "isRoleAction": false,
    "_id": 149,
    "cooldownGroup": 1,
    "castTime": 0,
    "icon": "000466"
  },
  {
    "costType": 3,
    "cost": 8,
    "name": "Thunder",
    "recastTime": 25,
    "level": 6,
    "isRoleAction": false,
    "_id": 144,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000457"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Addle",
    "recastTime": 900,
    "level": 8,
    "isRoleAction": true,
    "_id": 7560,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000861"
  },
  {
    "costType": 3,
    "cost": 10,
    "name": "Sleep",
    "recastTime": 25,
    "level": 10,
    "isRoleAction": false,
    "_id": 145,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000465"
  },
  {
    "costType": 3,
    "cost": 8,
    "name": "Blizzard II",
    "recastTime": 25,
    "level": 12,
    "isRoleAction": false,
    "_id": 146,
    "cooldownGroup": 58,
    "castTime": 20,
    "icon": "000455"
  },
  {
    "costType": 3,
    "cost": 0,
    "name": "Break",
    "recastTime": 25,
    "level": 12,
    "isRoleAction": true,
    "_id": 7558,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000862"
  },
  {
    "costType": 3,
    "cost": 8,
    "name": "Scathe",
    "recastTime": 25,
    "level": 15,
    "isRoleAction": false,
    "_id": 156,
    "cooldownGroup": 58,
    "castTime": 0,
    "icon": "000462"
  },
  {
    "costType": 3,
    "cost": 5,
    "name": "Drain",
    "recastTime": 25,
    "level": 16,
    "isRoleAction": true,
    "_id": 7564,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000863"
  },
  {
    "costType": 3,
    "cost": 15,
    "name": "Fire II",
    "recastTime": 25,
    "level": 18,
    "isRoleAction": false,
    "_id": 147,
    "cooldownGroup": 58,
    "castTime": 30,
    "icon": "000452"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Diversion",
    "recastTime": 1200,
    "level": 20,
    "isRoleAction": true,
    "_id": 7545,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000827"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Lucid Dreaming",
    "recastTime": 1200,
    "level": 24,
    "isRoleAction": true,
    "_id": 7562,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000865"
  },
  {
    "costType": 3,
    "cost": 12,
    "name": "Thunder II",
    "recastTime": 25,
    "level": 26,
    "isRoleAction": false,
    "_id": 7447,
    "cooldownGroup": 58,
    "castTime": 30,
    "icon": "000468"
  },
  {
    "costType": 1,
    "cost": 20,
    "name": "Convert",
    "recastTime": 1800,
    "level": 30,
    "isRoleAction": false,
    "_id": 158,
    "cooldownGroup": 11,
    "castTime": 0,
    "icon": "002651"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Manaward",
    "recastTime": 1200,
    "level": 30,
    "isRoleAction": false,
    "_id": 157,
    "cooldownGroup": 8,
    "castTime": 0,
    "icon": "000463"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Swiftcast",
    "recastTime": 600,
    "level": 32,
    "isRoleAction": true,
    "_id": 7561,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000866"
  },
  {
    "costType": 3,
    "cost": 20,
    "name": "Fire III",
    "recastTime": 25,
    "level": 34,
    "isRoleAction": false,
    "_id": 152,
    "cooldownGroup": 58,
    "castTime": 35,
    "icon": "000453"
  },
  {
    "costType": 3,
    "cost": 20,
    "name": "Freeze",
    "recastTime": 25,
    "level": 35,
    "isRoleAction": false,
    "_id": 159,
    "cooldownGroup": 58,
    "castTime": 30,
    "icon": "002653"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Mana Shift",
    "recastTime": 1200,
    "level": 36,
    "isRoleAction": true,
    "_id": 7565,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000867"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Apocatastasis",
    "recastTime": 900,
    "level": 40,
    "isRoleAction": true,
    "_id": 7563,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000868"
  },
  {
    "costType": 3,
    "cost": 12,
    "name": "Blizzard III",
    "recastTime": 25,
    "level": 40,
    "isRoleAction": false,
    "_id": 154,
    "cooldownGroup": 58,
    "castTime": 35,
    "icon": "000456"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Surecast",
    "recastTime": 300,
    "level": 44,
    "isRoleAction": true,
    "_id": 7559,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000869"
  },
  {
    "costType": 3,
    "cost": 16,
    "name": "Thunder III",
    "recastTime": 25,
    "level": 45,
    "isRoleAction": false,
    "_id": 153,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "000459"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Erase",
    "recastTime": 900,
    "level": 48,
    "isRoleAction": true,
    "_id": 7566,
    "cooldownGroup": 25,
    "castTime": 0,
    "icon": "000870"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Aetherial Manipulation",
    "recastTime": 300,
    "level": 50,
    "isRoleAction": false,
    "_id": 155,
    "cooldownGroup": 4,
    "castTime": 0,
    "icon": "000467"
  },
  {
    "costType": 4,
    "cost": 10,
    "name": "Flare",
    "recastTime": 25,
    "level": 50,
    "isRoleAction": false,
    "_id": 162,
    "cooldownGroup": 58,
    "castTime": 40,
    "icon": "002652"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Ley Lines",
    "recastTime": 900,
    "level": 52,
    "isRoleAction": false,
    "_id": 3573,
    "cooldownGroup": 7,
    "castTime": 0,
    "icon": "002656"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Sharpcast",
    "recastTime": 600,
    "level": 54,
    "isRoleAction": false,
    "_id": 3574,
    "cooldownGroup": 5,
    "castTime": 0,
    "icon": "002657"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Enochian",
    "recastTime": 300,
    "level": 56,
    "isRoleAction": false,
    "_id": 3575,
    "cooldownGroup": 3,
    "castTime": 0,
    "icon": "002658"
  },
  {
    "costType": 3,
    "cost": 8,
    "name": "Blizzard IV",
    "recastTime": 25,
    "level": 58,
    "isRoleAction": false,
    "_id": 3576,
    "cooldownGroup": 58,
    "castTime": 28,
    "icon": "002659"
  },
  {
    "costType": 3,
    "cost": 10,
    "name": "Fire IV",
    "recastTime": 25,
    "level": 60,
    "isRoleAction": false,
    "_id": 3577,
    "cooldownGroup": 58,
    "castTime": 28,
    "icon": "002660"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Between the Lines",
    "recastTime": 30,
    "level": 62,
    "isRoleAction": false,
    "_id": 7419,
    "cooldownGroup": 2,
    "castTime": 0,
    "icon": "002661"
  },
  {
    "costType": 3,
    "cost": 18,
    "name": "Thunder IV",
    "recastTime": 25,
    "level": 64,
    "isRoleAction": false,
    "_id": 7420,
    "cooldownGroup": 58,
    "castTime": 30,
    "icon": "002662"
  },
  {
    "costType": 0,
    "cost": 0,
    "name": "Triplecast",
    "recastTime": 600,
    "level": 66,
    "isRoleAction": false,
    "_id": 7421,
    "cooldownGroup": 16,
    "castTime": 0,
    "icon": "002663"
  },
  {
    "costType": 18,
    "cost": 0,
    "name": "Foul",
    "recastTime": 25,
    "level": 70,
    "isRoleAction": false,
    "_id": 7422,
    "cooldownGroup": 58,
    "castTime": 25,
    "icon": "002664"
  }
],
}
